### PR TITLE
refactor ProcessFiles; update Parse and Rep

### PR DESCRIPTION
**Pull request by fosler**

### CODE REVIEW

**Comment by fosler** [comment]
Version 3.1.0?

**Comment by StoneyJackson** [comment]
Closes #32 .

**Comment by StoneyJackson** [comment]
Here is a draft the merge commit message and CHANGELOG entry.

@fosler - Please confirm that I have accurately captured the changes that are included in this pull request.

---

## 3.1.0

* Issue [#32](https://github.com/ourPLCC/plcc/issues/32)
* PR [#33](https://github.com/ourPLCC/plcc/pull/33)

### Features

* Add `-v` "verbose" option

    I also want to suggest adding a '-v' (for "verbose") flag on the
    Parse/Rep command line. Setting this flag turns on printing the name
    of the command-line file in which the current expression is being
    parsed/evaluated, using the name "stdin" when reading from
    System.in. Here is an example from the OBJ language:

    Without the '-v' switch:

        java -cp Java Rep Prog/oe
        c
        1
        0
        1
        --> .<c>even?(6)
        1

    With the '-v' switch:

        java -cp Java Rep -v Prog/oe
        [Prog/oe]c
        [Prog/oe]1
        [Prog/oe]0
        [Prog/oe]1
        --> .<c>even?(6)
        [stdin]1

    The '-v' switch is particularly useful when there are several files
    on the command line and you need to find the one where a particular
    error occurs. This is a simple addition and does not break prior
    behaviors.


### Refactors

* Make `Rep` and `Parse` subclasses of `ProcessFiles`

  In VERSION 3.0.0, Parse and Rep both invoke main static method in
  ProcessFiles using a parseOnly parameter that distinguishes between
  just parsing (Parse, with parseOnly=true) and parsing and running
  (Rep, with parseOnly=false). In ProcessFiles, the main method calls a
  run() static method that uses an if statement that invokes either
  $ok() or $run() on the parse tree (an instanceƒ of _Start), depending
  on the value of parseOnly.

  I don't like using if statements if they can be avoided using
  subclassing, so I recommend that we change Rep and Parse so that they
  are subclasses of ProcessFiles, and then they can appropriately call
  the right action -- $ok() or $run() -- without needing to pass a flag.
  This will not have any effects on behavior; it simply makes better
  sense from an OO point of view.

  Oh, and I have taken the two very similar code blocks in ProcessFiles
  and factored them into a single method, processFile, which reduces the
  code size and helps to maintain consistency.

**Comment by fosler** [comment]
Confirmed.

**Review by StoneyJackson — APPROVED** [review]

**Pull request merged**
