### PR TITLE
Tune-up of Token processing and error reporting

### PR DESCRIPTION
**Pull request by fosler**
Add PLCCExceptions to replace RuntimeExceptions
Detect regular expression compile errors
Do better error reporting for parse errors
Replace Token.Val with Token.Match

### CODE REVIEW

**Comment by StoneyJackson** [comment]
Somehow the code in src/plcc.py to handle the `--version` option got deleted. 5edd510 restores it.

**Comment by StoneyJackson** [comment]
To update your copy...

```bash
git checkout matching
git pull
```

**Review by StoneyJackson — COMMENTED** [review]
I'm happy.

I'll leave it to @jashelio for final approval.

**Comment by fosler** [comment]
Concerning Jim's comment regarding the arbno separator: in `plcc.py`, line 399, I suggest that we replace "final separator in an arbno rule must be a Terminal" with "final separator in a repeating rule must be a bare Token". In addition, I suggest that we replace "arbno" with "repeating" in all other error message strings in `plcc.py` (but nowhere else).

**Comment by StoneyJackson** [comment]
@fosler Sounds like a good idea. If you want to make the change, here is a rough sketch of what you need to do with git...

```bash
cd /root/of/plcc/clone

# Ensure you are working on matching
git checkout matching

# Update your copy with the changes I pushed up yesterday
git pull

# Make your changes...
vi ...

# Stage all changes in the current directory and all subdirectories recursively
git add .

# Commit them
git commit

# Push them, which will automatically update this pull-request.
git push
```

If @jashelio later hates the idea, we can use git to revert the change. So no worries.

**Comment by fosler** [comment]
What's the 'update-shell' branch?

**Comment by StoneyJackson** [comment]
This pull request hasn't been merges. I assume that you didn't mean to close it. So I'm reopening it.

**Comment by StoneyJackson** [comment]
The "update-shell" branch is part of this pull-request (PR): https://github.com/ourPLCC/plcc/pull/27 . In that PR, I'm trying to enable [continuous integration](https://docs.github.com/en/actions/guides/about-continuous-integration). It should not interfere with what you are doing here.

In the future, it will run all the automated tests each time someone pushes to a branch associated with a pull-request.

**Comment by jashelio** [comment]
By the way, I am happy with Tim's suggestion for this additional change.

Jim

**Comment by StoneyJackson** [comment]
@fosler Does your last commit resolve https://github.com/ourPLCC/plcc/issues/24 ? If so, I'll link it to this PR.

**Pull request merged**
