### PR TITLE
refactor!: Reorganize files

### PR DESCRIPTION
**Pull request by StoneyJackson**
BREAKING CHANGE:
Moves all source files into a subdirectory named src within the PLCC project.
The path to this src directory is what the LIBPLCC environment variable must
point to, and is also the path that must be added to the PATH environment
variable.  When upgrading, these environment variables must be manually
adjusted to point to the new src directory.

### CODE REVIEW

**Comment by StoneyJackson** [comment]
Here are some install instructions for the new file structure. These will replace those on the wiki: https://github.com/ourPLCC/plcc/wiki/Install .

---

## Installation options

There are two options for installing and using PLCC.

1. Install and use PLCC natively. See below.
2. Install and use PLCC through Docker. See [PLCC-in-Docker](https://github.com/ourPLCC/plcc-in-docker).

## Installing PLCC natively
> Version 2.0.0 or above

1. Install Java JDK 5 or higher (we recommend OpenJDK 11).
2. Install Python 3.8 or higher
3. Download a zip of the desired version of PLCC from the [PLCC Releases page](https://github.com/ourPLCC/plcc/releases).
4. Extract the zip to a location where you want the home of PLCC to be located.
5. Identify the PLCC's `src` directory within the directory (or subdirectories) created when you extracted the zip.
6. Define a new environment variable named PLCCLIB whose value is the full path to PLCC's src directory.
7. Add the full path to PLCC's src directory to beginning of the PATH environment variable.

**Comment by StoneyJackson** [comment]
This pull request is associated with the `reorganize` branch. To test code in this branch on your local machine, clone PLCC to some temporary location and checkout `reorganize` as follows.

```bash
git clone https://github.com/ourPLCC/plcc.git
cd plcc
git checkout reorganize
```

Now you can test all you like. When you are done, just delete the plcc directory created by the clone command.

**Comment by fosler** [comment]
It should be "LIBPLCC" instead of "PLCCLIB". Please verify.

**Comment by StoneyJackson** [comment]
> It should be "LIBPLCC" instead of "PLCCLIB". Please verify.

Verified. You are correct, sir. Good catch! Fixing documentation now.

**Pull request merged**
